In [2]:
# 라이브러리 불러오기
import pandas as pd
import numpy as np 

# read_csv() 함수로 df 생성
df = pd.read_csv('../dataset/mpg/auto-mpg.csv', header=None)
print(df.shape,'\n')
print(df.head(3), '\n')

# 열이름을 지정
df.columns = ['mpg', 'cylinders', 'displacement', 'horsepower',
             'weight', 'acceleration', 'model_year', 'origin', 'name']

# horsepower 열의 누락 데이터('?') 삭제하고 실수형으로 변환
df['horsepower'].replace('?', np.nan, inplace=True) # '?'을 np.nan으로 변경
df.dropna(subset=['horsepower'], axis=0, inplace=True) # 누락데이터 행을 삭제
df['horsepower'] = df['horsepower'].astype('float') # 문자열을 실수형으로 변환
df['horsepower'].unique()

(398, 9) 

      0  1      2      3       4     5   6  7                          8
0  18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1  15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2  18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite 



array([130., 165., 150., 140., 198., 220., 215., 225., 190., 170., 160.,
        95.,  97.,  85.,  88.,  46.,  87.,  90., 113., 200., 210., 193.,
       100., 105., 175., 153., 180., 110.,  72.,  86.,  70.,  76.,  65.,
        69.,  60.,  80.,  54., 208., 155., 112.,  92., 145., 137., 158.,
       167.,  94., 107., 230.,  49.,  75.,  91., 122.,  67.,  83.,  78.,
        52.,  61.,  93., 148., 129.,  96.,  71.,  98., 115.,  53.,  81.,
        79., 120., 152., 102., 108.,  68.,  58., 149.,  89.,  63.,  48.,
        66., 139., 103., 125., 133., 138., 135., 142.,  77.,  62., 132.,
        84.,  64.,  74., 116.,  82.])

In [3]:
# np.histogram 함수로 3개의 bin으로 나누는 경계 값의 리스트 구하기
print(df['horsepower'].size)
count, bin_dividers = np.histogram(df['horsepower'], bins=3)

print(bin_dividers.size, '\t', bin_dividers, '\t', count, '\n')

np.histogram(df['horsepower'], bins=3)

392
4 	 [ 46.         107.33333333 168.66666667 230.        ] 	 [257 103  32] 



(array([257, 103,  32], dtype=int64),
 array([ 46.        , 107.33333333, 168.66666667, 230.        ]))

In [4]:
# 3개의 bin에 이름 지정
bin_names = ['저출력', '보통출력', '고출력']

# pd.cut 함수로 각 데이터를 3개의 bin에 할당
df['hp_bin'] = pd.cut(x=df['horsepower'],  # 데이터 배열
                     bins = bin_dividers,  # 경계 값 리스트
                     labels = bin_names,  # bin 이름
                     include_lowest = True)  # 첫 경계값 포함

# horsepower 열, hp_bin 열의 첫 15행을 출력
print(df[['horsepower', 'hp_bin']].head(15))
print(df[['horsepower', 'hp_bin']].tail(15))

    horsepower hp_bin
0        130.0   보통출력
1        165.0   보통출력
2        150.0   보통출력
3        150.0   보통출력
4        140.0   보통출력
5        198.0    고출력
6        220.0    고출력
7        215.0    고출력
8        225.0    고출력
9        190.0    고출력
10       170.0    고출력
11       160.0   보통출력
12       150.0   보통출력
13       225.0    고출력
14        95.0    저출력
     horsepower hp_bin
383        67.0    저출력
384        67.0    저출력
385        67.0    저출력
386       110.0   보통출력
387        85.0    저출력
388        92.0    저출력
389       112.0   보통출력
390        96.0    저출력
391        84.0    저출력
392        90.0    저출력
393        86.0    저출력
394        52.0    저출력
395        84.0    저출력
396        79.0    저출력
397        82.0    저출력
