In [1]:
# numpy & pandas 함수별 axis 옵션 차이 [통일 안됨]
# 코딩시 axis 옵션이 반대로 작동하는 경우 정리

In [17]:
# delete와 drop
# delete, drop 에서는 0 axis가 행이고, 1 axis가 열이 된다.
import numpy as np
import pandas as pd

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr)

print(arr,'\n')

print(np.delete(arr,0,axis = 0),'\n')
print(np.delete(arr,0,axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[4 5 6]
 [7 8 9]] 

[[2 3]
 [5 6]
 [8 9]]


In [3]:
print(df.drop(0, axis = 0))
print(df.drop(0, axis = 1))

   0  1  2
1  4  5  6
2  7  8  9
   1  2
0  2  3
1  5  6
2  8  9


In [14]:
# sum, apply 함수 경우
# sum에서는 0 axis는 열을 의미하고, 1 axis는 행을 의미
import numpy as np
import pandas as pd

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr)

print(arr,"\n")

print(arr.sum(axis = 0), '\n')
print(arr.sum(axis = 1), '\n\n')

print(df.sum(axis = 0), '\n')
print(df.sum(axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[12 15 18] 

[ 6 15 24] 


0    12
1    15
2    18
dtype: int64 

0     6
1    15
2    24
dtype: int64
