In [1]:
import numpy as np
data1 = [1,2,3,4,5]

# np 배열 생성
arr1 = np.array(data1)

# 1차원 배열
arr1

array([1, 2, 3, 4, 5])

In [2]:
# 자료형
print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
# 배열의 차원
arr1.shape

(5,)

In [4]:
# 2차원 배열
# 스트링 리스트를 넘파이 배열로 변환
data2 = [[1,2,3],[4,5,6]]

# 2차원 리스트를 넘파이 2차원 행렬로 변환
arr2 = np.array(data2)
print(arr2)

# 2행 3열 2차원 행렬 확인
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
