In [1]:
import numpy as np

# 5행 4열의 랜덤값 생성
arr = np.random.randn(5,4)
arr

array([[-0.51720495, -0.4931791 , -0.30803151, -0.1426198 ],
       [ 1.47421802,  2.16020441, -0.97505372,  0.14326447],
       [-1.06961768,  1.12129192, -1.43037517,  1.05320784],
       [-1.61702688, -0.84108863,  0.81408215,  0.16236773],
       [-1.56084789,  1.35599868,  0.7257708 , -0.92594805]])

In [5]:
# 각 열의 합계
arr.sum(axis=0)

array([-3.29047938,  3.30322728, -1.17360745,  0.29027219])

In [6]:
# 각 행의 합계
arr.sum(axis=1)

array([-1.46103536,  2.80263318, -0.32549308, -1.48166563, -0.40502647])