In [1]:
import numpy as np

# numpy 배열의 연산
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [2]:
arr1 - arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [3]:
arr1 * arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [4]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])